/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JLabel;

/**
 *
 * @author ninomc
 */
public class VistaCambioBits extends javax.swing.JFrame {

    private int x;
    private int y;
    public JLabel[][] codeWord; 
    private JLabel codeWordNumber = new JLabel();
    
    /**
     * Creates new form NewJFrame
     */
    public VistaCambioBits() {
        
        initComponents();
        this.setTitle("Cambio de bits");
    }

    private void iniciar(){
        
        codeWord = new JLabel[x][y];
        
        for(int i=0; i < x; i++){
                        
            for(int j=0; j < y; j++){
                
                codeWord[i][j] = new JLabel();
                codeWord[i][j].setSize(10, 13);
                codeWord[i][j].setLocation (j*10+10, 60*i+35);
                codeWord[i][j].setVisible(true);
                codeWord[i][j].setForeground(Color.black);
                codeWord[i][j].setFont(new Font("Arimo", Font.BOLD, 15));
                codeWord[i][j].setCursor(new Cursor(Cursor.HAND_CURSOR));
                int a = i;
                int b = j;
                codeWord[i][j].addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent me) {

                        cambio(a, b);
                    }

                    @Override
                    public void mousePressed(MouseEvent me) {
                    }

                    @Override
                    public void mouseReleased(MouseEvent me) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent me) {
                    }

                    @Override
                    public void mouseExited(MouseEvent me) {
                    }
                });
                this.principal.add(this.codeWord[i][j]);
            }
            
            codeWordNumber = new JLabel();
            codeWordNumber.setText("\nCode Word numero "+String.valueOf(i+1)+": ");
            codeWordNumber.setSize(200, 15);
            codeWordNumber.setLocation(i+5, i*60+10);
            codeWordNumber.setVisible(true);
            codeWordNumber.setForeground(Color.blue);
            this.principal.add(codeWordNumber);
        }
        
        this.principal.updateUI();
    }
    
    public JLabel[][] getCodeWord(){
        
        return this.codeWord;
    }
    
    public void setXY(int x, int y){
        
        this.x = x;
        this.y = y;
        this.iniciar();
    }
    
    public int getXLabel(){
        return this.x;
    }
    
    public int getYLabel(){
        return this.y;
    }
    
    private void cambio(int i, int j){
        
        int value = Integer.parseInt(codeWord[i][j].getText());
        codeWord[i][j].setText(String.valueOf((value+1)%2));

        if(codeWord[i][j].getForeground() == Color.black){
            
            codeWord[i][j].setForeground(Color.red);
        }else{
            
            codeWord[i][j].setForeground(Color.black);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        principal = new javax.swing.JPanel();
        finishProcess = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        principal.setBackground(new java.awt.Color(255, 255, 255));

        finishProcess.setBackground(new java.awt.Color(242, 131, 107));
        finishProcess.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        finishProcess.setForeground(new java.awt.Color(255, 255, 255));
        finishProcess.setText("Terminar Cambios");
        finishProcess.setToolTipText("Presioname");
        finishProcess.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        finishProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishProcessActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(242, 131, 107));
        jButton3.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancelar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishProcess)
                .addContainerGap())
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishProcess)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishProcessActionPerformed

    }//GEN-LAST:event_finishProcessActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //this.;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCambioBits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCambioBits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCambioBits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCambioBits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCambioBits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton finishProcess;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
